spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

token:
  expiration_time: 86400000
  secret: potato_velog_default

gateway:
  ip: 127.0.0.1	